#+title: Emacs Org mode CSS for HTML export
#+options: toc:nil num:nil author:nil timestamp:nil ^:nil pri:t
#+setupfile: inline.css.org

A CSS file for [[https://orgmode.org/][Emacs Org mode]] HTML export that provides an easy to read style
suitable for smaller documents.

I've come to use Org mode for much of my work related planning and tracking
progress on tasks. Sometimes I'm requested to provide a report by email at which
time it's convenient to be able to export what's readily available in one of my
Org files. I also write longer emails in Org mode as I think it's easier to
create a decent structure.

See https://johan-bolmsjo.github.io/org_css/README.html for how this document is
rendered as HTML.

* CSS Usage

Use a block such as the following to specify document options and to inline the
CSS file into the exported HTML file.

#+begin_src org
  ,#+options: toc:nil num:nil author:nil timestamp:nil ^:nil
  ,#+setupfile: inline.css.org
#+end_src

I usually place the block after the Org document title. Export to HTML with the
command =M-x org-html-export-to-html=.

** Custom Fonts

A custom serif font is used for body text as I think the default serif font
used by web browsers is too dense.

A custom =monospace= font is used as the default mono space font /courier/ on
Windows results in a very different look compared to what is typically displayed
on Linux systems.

If you come to rely on this CSS file you are wise to provide your own font
source. See [[file:org.css][org.css]] for details.

** Disabling HTML Validation Link

Org mode exports a HTML validation link by default. There does not seem to be a
way to disable the link by using =#+options:= in the Org file. Add the following
to the Emacs init file to disable the generated HTML validation link.

#+begin_src emacs-lisp
  ;; HTML output: Don't emit validation link
  (setq org-html-validation-link nil)
#+end_src

* CSS Modifications

Edit the file [[file:org.css][org.css]] and update the file =inline.css.org= by running
=make=. The [[https://yui.github.io/yuicompressor/][YUI Compressor]] program is used to compress the CSS to reduce the
size of exported HTML files.

Example (Debian based Linux):
#+begin_src
  sudo apt-get install yui-compressor
  make
#+end_src

* Licensing Terms

This work is a derivative of https://github.com/gongzhitaao/orgcss.

The license files [[file:LICENSE.MIT][LICENSE.MIT]] and [[file:LICENSE.996][LICENSE.996ICU]] applies to =org.css=
and the derivative file =inline.css.org=.

The license file [[file:LICENSE.MIT][LICENSE.MIT]] applies to the remaining sources in the root
directory of this source distribution.

** Fonts
The license file [[file:fonts/Lora/OFL.txt][fonts/Lora/OFL.txt]] describes the terms under which the font
/Lora/ is distributed.

The license file [[file:fonts/Go-Mono/README][fonts/Go-Mono/README]] describes the terms under which the font
/Go Mono/ is distributed.

* Style Demonstration

A style demonstration of typographical elements not already employed by this
document.

** Block Quotes
#+begin_quote
At 19.00 hours, ship's time, I made my way to the launching bay. The men around
the shaft stood aside to let me pass, and I climbed down into the capsule. /--
Opening of the book Solaris by Stanislaw Lem/
#+end_quote

** Lists
*** Bullet List [2/3]
- [X] Wash the car
- [ ] Buy groceries
  + Milk
  + Bread
  + Bananas
- [X] Feed the dog

*** Numbered List
1. Dogs
   1. Akita
   2. Beagle
2. Cats
   1. Bengal

*** Definition List
- GNU :: GNU's Not Unix
- Unix :: Multitasking, multi-user operating system. Conceived at Bell Labs
  research center by Ken Thompson, Dennis Ritchie, and others in the 1970s.
- Linux :: Popular Unix like operating system kernel.

** Tables
#+CAPTION: Nutritional content per 100 g
| Grocery   | kcal | Carbs (g) | Protein (g) | Fat (g) |
|-----------+------+-----------+-------------+---------|
| Banana    |   95 |      21.3 |         1.1 |     0.1 |
| Milk (3%) |   60 |       4.7 |         3.5 |       3 |
| Pasta     |  360 |      71.9 |        12.5 |     1.2 |

** Org Keywords and Tags
*** TODO [#A] Do Laundry                                           :weekly:
DEADLINE: <2022-03-06 sön +1w>
*** DONE Cook Sunday Dinner
CLOSED: [2022-03-06 sön 15:47]
