#+title: Emacs Org mode CSS for HTML export
#+date: [2022-12-07]
#+options: date:t pri:t

A CSS file for [[https://orgmode.org/][Emacs Org mode]] HTML export that provides an easy to read style suitable for smaller documents.

I've come to use Org mode for much of my work related planning and tracking progress on tasks.
I also write longer emails in Org mode as I think it's easier to create a decent structure.
The Org mode HTML export is a convenient way to share such documents with less blessed individuals (non Org users).

See https://johan-bolmsjo.github.io/org_css/README.html for how this document is rendered as HTML.

* CSS Usage

Three CSS files are contained in this repository.
Files named /main/ contains non font related layout.
Files named /font/ attempts to use fonts hosted on my domain.
Finally, files named /full/ contains the previously mentioned files concatenated.

Versions of the CSS files named /optimized/ has been run through the =yui-compressor= to reduce their size.

Files with a =.css.el= post-fix are meant to be loaded either from an org-publish file or from =init.el= to embed CSS into exported HTML files.
See how this is done in =./org-publish.el=.

The org-publish file disables many export elements.
I like the default to be usable for small documents where these elements are excessive.
They can be enabled selectively by tweaking an Org file's =#+options:= line.
See https://orgmode.org/manual/Export-Settings.html for details.

Export an Org file to HTML with the command =M-x org-html-export-to-html=.

* CSS Modifications

Edit the CSS files according to taste.
Build using the =Makefile=.

The [[https://yui.github.io/yuicompressor/][YUI Compressor]] program is used to compress the CSS to reduce their size.

Example (Debian based Linux):
#+begin_src
  sudo apt-get install yui-compressor
  make
#+end_src

* Licensing Terms

This work is a derivative of https://github.com/gongzhitaao/orgcss.

The license files [[file:LICENSE.MIT][LICENSE.MIT]] and [[file:LICENSE.996][LICENSE.996ICU]] applies to =org.css=
and the derivative file =inline.css.org=.

The license file [[file:LICENSE.MIT][LICENSE.MIT]] applies to the remaining sources in the root
directory of this source distribution.

** Fonts
The license file [[file:fonts/Lora/OFL.txt][fonts/Lora/OFL.txt]] describes the terms under which the font
/Lora/ is distributed.

The license file [[file:fonts/Inconsolata/OFL.txt][fonts/Inconsolata/OFL.txt]] describes the terms under which the font
/Inconsolata/ is distributed.

* Style Demonstration

A style demonstration of typographical elements not already employed by this document.

** Block Quotes
#+begin_quote
At 19.00 hours, ship's time, I made my way to the launching bay.
The men around the shaft stood aside to let me pass, and I climbed down into the capsule.
/-- Opening of the book Solaris by Stanislaw Lem/
#+end_quote

** Lists
*** Bullet List [2/3]
- [X] Wash the car
- [ ] Buy groceries
  + Milk
  + Bread
  + Bananas
- [X] Feed the dog

*** Numbered List
1. Dogs
   1. Akita
   2. Beagle
2. Cats
   1. Bengal

*** Definition List
- GNU :: GNU's Not Unix
- Unix :: Multitasking, multi-user operating system. Conceived at Bell Labs
  research center by Ken Thompson, Dennis Ritchie, and others in the 1970s.
- Linux :: Popular Unix like operating system kernel.

** Tables
#+CAPTION: Nutritional content per 100 g
| Grocery   | kcal | Carbs (g) | Protein (g) | Fat (g) |
|-----------+------+-----------+-------------+---------|
| Banana    |   95 |      21.3 |         1.1 |     0.1 |
| Milk (3%) |   60 |       4.7 |         3.5 |       3 |
| Pasta     |  360 |      71.9 |        12.5 |     1.2 |

** Org Keywords and Tags
*** TODO [#A] Do Laundry                                           :weekly:
DEADLINE: <2022-03-06 sön +1w>
*** DONE Cook Sunday Dinner
CLOSED: [2022-03-06 sön 15:47]
